# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

homepage:
    pattern: /
    defaults: { _controller: VichSf2TweetsBundle:Tweet:getTweets }
    
_tweet:
    resource: "Vich\Sf2TweetsBundle\Controller\TweetController"
    type: rest